import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../public/globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import AudioPlayer from "@/components/audio/AudioPlayer";
import AuthWatcher from "@/components/authwatcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthWatcher />
      <body className={inter.className}>
        <main className="h-screen flex flex-col justify-between bg-[#170f23]">
          <div className="h-[calc(100%_-_84px)] flex">
            <Sidebar />
            <div className="w-full h-full">
              <Header />
              {children}
            </div>
          </div>
          <div className="h-[84px]">
            <AudioPlayer
              audioSource={
                "https://vnso-zn-23-tf-a320-zmp3.zmdcdn.me/a5e0debc57e4d8a6fd251b8835df717a?authen=exp=1701971212~acl=/a5e0debc57e4d8a6fd251b8835df717a/*~hmac=353a1aff8eb71658a72f7463d78cbae5"
              }
            />
          </div>
        </main>
      </body>
    </html>
  );
}
