import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../public/globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import AudioPlayer from "@/components/audio/AudioPlayer";
import AuthWatcher from "@/components/authwatcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthWatcher />
      <body className={inter.className}>
        <main className="h-screen flex bg-[#170f23]">
          <Sidebar />
          <div className="w-full h-full">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
